var fruits = ["banana", "apple", "orange", "watermelon"];
var vegetables = ["carrot", "tomato", "pepper", "lettuce"];
poppedVeg = vegetables.pop()
console.log(poppedVeg, vegetables)
firstFruit = fruits.shift()
console.log(firstFruit, fruits)
index = fruits.indexOf("orange")
console.log(index)
fruits.push(1)
console.log(fruits)
console.log(vegetables.length)
vegetables.push(3)
console.log(vegetables)
var food = fruits.concat(vegetables)
console.log(food)
removedFood = food.splice(4, 2)
console.log(removedFood, food)
reverseFood = food.reverse()
console.log(reverseFood)
foods = reverseFood.join(",")
console.log(foods)